Added encoder support, fixed keymap between via and Cory Dora mapping QK_BOOT to flash
balub/qmk_firmware pull request #1
Opened 2024-09-22 22:52 UTC by layogtima

## Description

Changes,
- Rotary encoder for Cory Dora should now as expected (added mappings and reasonable defaults)
- Via / QMK mappings now match for the Cory Dora
- QK_BOOT to flash is now enabled to Key 9, profile #4 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [✔] Keyboard (addition or update)
- [✔] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [✔] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [✔] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [✔] My change requires a change to the documentation.
- [✔] I have updated the documentation accordingly.
- [✔] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [✔] I have added tests to cover my changes.
- [✔] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-09-22 22:53 UTC, layogtima commented
@balub see if this works!

2024-10-08 21:54 UTC, balub requested changes

2024-10-08 21:54 UTC, balub commented on keyboards/handwired/corydora/via.json
> +            ["2,0", "2,1", "2,2", "3,0\n\n\n\n\n\n\n\n\ne0"]
```suggestion
            ["2,0", "2,1", "2,2", "3,0"]
```

2024-10-09 13:05 UTC, layogtima commented
Removed redundant config repeats. Fixed the via.json file issue; rows need to be 4!

2024-10-10 20:39 UTC, balub approved these changes
LGTM 🚀

2024-10-10 20:40 UTC, merged